### ISSUE TITLE
Error on rename when `nw install` on Windows 10 64bit

### ISSUE THREAD

**Issue by timfish** [egoist/nwjs#16]
```

C:\Users\tim\Documents>nw install 0.16.1
Downloading 0.16.1.zip
[============================================>] 100.0% of 51.75 MB (2.01 MB/s)
shell.js: internal error
Error: EPERM: operation not permitted, rename 'C:\Users\tim\.nwjs\nwjs-v0.16.1-win-x64' -> 'C:\Users\tim\.nwjs\0.16.1'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at C:\Users\tim\AppData\Roaming\npm\node_modules\nwjs\node_modules\shelljs\src\mv.js:79:8
    at Array.forEach (native)
    at _mv (C:\Users\tim\AppData\Roaming\npm\node_modules\nwjs\node_modules\shelljs\src\mv.js:55:11)
    at C:\Users\tim\AppData\Roaming\npm\node_modules\nwjs\node_modules\shelljs\src\common.js:240:23
    at Command.<anonymous> (C:\Users\tim\AppData\Roaming\npm\node_modules\nwjs\lib\install.js:40:5)
    at next (native)
    at onFulfilled (C:\Users\tim\AppData\Roaming\npm\node_modules\nwjs\node_modules\co\index.js:65:19)

```

I've tried messing around deleting the directory or opening up permissions with no luck. In the end I renamed the directory myself to get it working...

**Comment by timfish** [comment]
For some reason `nw install 0.16.1-sdk` didn't have this issue...

**Comment by karikera** [comment]
It happened to me.
I think this occur randomly..

**Comment by fritx** [comment]
```plain
Error: EPERM: operation not permitted, rename 'C:\Users\tim\.nwjs\nwjs-v0.16.1-win-x64' -> 'C:\Users\tim\.nwjs\0.16.1'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at C:\Users\tim\AppData\Roaming\npm\node_modules\nwjs\node_modules\shelljs\src\mv.js:79:8
```

Seems like it's an error caused by `shelljs.mv`.
And I found the newest version of `mv` includes a `try/catch` on `fs.renameSync`:
https://github.com/shelljs/shelljs/blob/master/src/mv.js#L82-L91

**Comment by timfish** [comment]
Looks like it might fix it. I still get this every time I do an install. Luckily I dont do that very often!

**Comment by megapctr** [comment]
I was having the same issue, here's a dirty trick to fix it (basically you manually upgrade nwjs's shelljs dependency)
```
$ npm install shelljs@latest
$ rm -r node_modules/nwjs/node_modules/shelljs/
$ mv node_modules/shelljs/ node_modules/nwjs/node_modules/
```

And then finally
```
$ nw install 0.19.4-sdk
Downloading 0.19.4-sdk.zip
[============================================>] 100.0% of 84.58 MB (1.26 MB/s)
√ Version 0.19.4-sdk is installed and activated
```

**Comment by Klemen1337** [comment]
+ 1 I have the same problem
